steps:
  - label: ":hammer: Build and Test"
    plugins:
      - docker#v5.8.0:
          image: "ubuntu:latest"
          shell: ["/bin/bash", "-e", "-c"]
    env:
      DEBIAN_FRONTEND: "noninteractive"
    command: ".buildkite/build.sh"
